db.connectionString=jdbc:postgresql://localhost:5432/simulacion_db
db.user=postgres
db.password=27418291
simulacion.cantidadMuestras=8
simulacion.maxReintentos=3
simulacion.query=SELECT 1
pool.maxConnections=5
pool.minConnections=2
